In [4]:
import pandas as pd
URL = "https://en.wikipedia.org/wiki/List_of_world_records_in_swimming"

In [6]:
import pandas as pd
print(pd.__version__)

3.0.3

In [9]:
import requests

r = requests.get(
    "https://en.wikipedia.org/wiki/List_of_world_records_in_swimming",
    headers={"User-Agent": "Mozilla/5.0"}
)

print(r.status_code)
print(r.url)
print(r.headers.get("content-type"))

200
https://en.wikipedia.org/wiki/List_of_world_records_in_swimming
text/html; charset=UTF-8

In [36]:
from io import StringIO


html = requests.get(
    URL,
    headers={"User-Agent": "Mozilla/5.0"}
).text

tables = pd.read_html(StringIO(html))

In [13]:
tables[0].head()

,Event,Time,Unnamed: 2,Name,Nationality,Date,Meet,Location,Ref
0,50m freestyle,20.88,NaN,Cameron McEvoy,Australia,20 March 2026,China Open,"Shenzhen, China",[9]
1,100m freestyle,46.40,NaN,Pan Zhanle,China,31 July 2024,Olympic Games,"Paris, France",[10]
2,200m freestyle,1:42.00,ss,Paul Biedermann,Germany,28 July 2009,World Championships,"Rome, Italy",[11][12][13]
3,400m freestyle,3:39.96,NaN,Lukas Märtens,Germany,12 April 2025,Swim Open Stockholm,"Stockholm, Sweden",[14]
4,800m freestyle,7:32.12,ss,Zhang Lin,China,29 July 2009,World Championships,"Rome, Italy",[15][16]

In [15]:
df = tables[0][["Event", "Time"]]

In [16]:
df.head()

            Event     Time
0   50m freestyle    20.88
1  100m freestyle    46.40
2  200m freestyle  1:42.00
3  400m freestyle  3:39.96
4  800m freestyle  7:32.12

In [17]:
df.to_dict()

{'Event': {0: '50m freestyle',
  1: '100m freestyle',
  2: '200m freestyle',
  3: '400m freestyle',
  4: '800m freestyle',
  5: '1500m freestyle',
  6: '50m backstroke',
  7: '100m backstroke',
  8: '200m backstroke',
  9: '50m breaststroke',
  10: '100m breaststroke',
  11: '200m breaststroke',
  12: '50m butterfly',
  13: '100m butterfly',
  14: '200m butterfly',
  15: '200m individual medley',
  16: '400m individual medley',
  17: '4 × 100 m freestyle relay',
  18: '4 × 200 m freestyle relay',
  19: '4 × 100 m medley relay'},
 'Time': {0: '20.88',
  1: '46.40',
  2: '1:42.00',
  3: '3:39.96',
  4: '7:32.12',
  5: '14:30.67',
  6: '23.55',
  7: '51.60',
  8: '1:51.92',
  9: '25.95',
  10: '56.88',
  11: '2:05.48',
  12: '22.27',
  13: '49.45',
  14: '1:50.34',
  15: '1:52.69',
  16: '4:02.50',
  17: '3:08.24',
  18: '6:58.55',
  19: '3:26.78'}}

In [18]:
df.tail()

                        Event     Time
15     200m individual medley  1:52.69
16     400m individual medley  4:02.50
17  4 × 100 m freestyle relay  3:08.24
18  4 × 200 m freestyle relay  6:58.55
19     4 × 100 m medley relay  3:26.78

In [19]:
df[df["Event"].str.contains("relay")]

                        Event     Time
17  4 × 100 m freestyle relay  3:08.24
18  4 × 200 m freestyle relay  6:58.55
19     4 × 100 m medley relay  3:26.78

In [20]:
df[~df["Event"].str.contains("relay")]

                     Event      Time
0            50m freestyle     20.88
1           100m freestyle     46.40
2           200m freestyle   1:42.00
3           400m freestyle   3:39.96
4           800m freestyle   7:32.12
5          1500m freestyle  14:30.67
6           50m backstroke     23.55
7          100m backstroke     51.60
8          200m backstroke   1:51.92
9         50m breaststroke     25.95
10       100m breaststroke     56.88
11       200m breaststroke   2:05.48
12           50m butterfly     22.27
13          100m butterfly     49.45
14          200m butterfly   1:50.34
15  200m individual medley   1:52.69
16  400m individual medley   4:02.50

In [21]:
df = df[~df["Event"].str.contains("relay")]

In [22]:
df.to_dict("records")

[{'Event': '50m freestyle', 'Time': '20.88'},
 {'Event': '100m freestyle', 'Time': '46.40'},
 {'Event': '200m freestyle', 'Time': '1:42.00'},
 {'Event': '400m freestyle', 'Time': '3:39.96'},
 {'Event': '800m freestyle', 'Time': '7:32.12'},
 {'Event': '1500m freestyle', 'Time': '14:30.67'},
 {'Event': '50m backstroke', 'Time': '23.55'},
 {'Event': '100m backstroke', 'Time': '51.60'},
 {'Event': '200m backstroke', 'Time': '1:51.92'},
 {'Event': '50m breaststroke', 'Time': '25.95'},
 {'Event': '100m breaststroke', 'Time': '56.88'},
 {'Event': '200m breaststroke', 'Time': '2:05.48'},
 {'Event': '50m butterfly', 'Time': '22.27'},
 {'Event': '100m butterfly', 'Time': '49.45'},
 {'Event': '200m butterfly', 'Time': '1:50.34'},
 {'Event': '200m individual medley', 'Time': '1:52.69'},
 {'Event': '400m individual medley', 'Time': '4:02.50'}]

In [23]:
df = df.set_index("Event")
df.head()

                   Time
Event
50m freestyle     20.88
100m freestyle    46.40
200m freestyle  1:42.00
400m freestyle  3:39.96
800m freestyle  7:32.12

In [24]:
df.to_dict()

{'Time': {'50m freestyle': '20.88',
  '100m freestyle': '46.40',
  '200m freestyle': '1:42.00',
  '400m freestyle': '3:39.96',
  '800m freestyle': '7:32.12',
  '1500m freestyle': '14:30.67',
  '50m backstroke': '23.55',
  '100m backstroke': '51.60',
  '200m backstroke': '1:51.92',
  '50m breaststroke': '25.95',
  '100m breaststroke': '56.88',
  '200m breaststroke': '2:05.48',
  '50m butterfly': '22.27',
  '100m butterfly': '49.45',
  '200m butterfly': '1:50.34',
  '200m individual medley': '1:52.69',
  '400m individual medley': '4:02.50'}}

In [26]:
records = {}
records["LC Men"] = df.to_dict()["Time"]

In [27]:
records

{'LC Men': {'50m freestyle': '20.88',
  '100m freestyle': '46.40',
  '200m freestyle': '1:42.00',
  '400m freestyle': '3:39.96',
  '800m freestyle': '7:32.12',
  '1500m freestyle': '14:30.67',
  '50m backstroke': '23.55',
  '100m backstroke': '51.60',
  '200m backstroke': '1:51.92',
  '50m breaststroke': '25.95',
  '100m breaststroke': '56.88',
  '200m breaststroke': '2:05.48',
  '50m butterfly': '22.27',
  '100m butterfly': '49.45',
  '200m butterfly': '1:50.34',
  '200m individual medley': '1:52.69',
  '400m individual medley': '4:02.50'}}

In [41]:
RECORDS = (0, 1, 3, 4)
COURSES = ("LC Men", "LC Women", "SC Men", "SC Women")

records = {}
for table , course in zip(RECORDS, COURSES):
    df = tables[table][["Event", "Time"]]
    df = df[~df["Event"].str.contains("relay")]
    df = df.set_index("Event")
    records[course] = df.to_dict()["Time"]

In [42]:
records

{'LC Men': {'50m freestyle': '20.88',
  '100m freestyle': '46.40',
  '200m freestyle': '1:42.00',
  '400m freestyle': '3:39.96',
  '800m freestyle': '7:32.12',
  '1500m freestyle': '14:30.67',
  '50m backstroke': '23.55',
  '100m backstroke': '51.60',
  '200m backstroke': '1:51.92',
  '50m breaststroke': '25.95',
  '100m breaststroke': '56.88',
  '200m breaststroke': '2:05.48',
  '50m butterfly': '22.27',
  '100m butterfly': '49.45',
  '200m butterfly': '1:50.34',
  '200m individual medley': '1:52.69',
  '400m individual medley': '4:02.50'},
 'LC Women': {'50m freestyle': '23.61',
  '100m freestyle': '51.71',
  '200m freestyle': '1:52.23',
  '400m freestyle': '3:54.18',
  '800m freestyle': '8:04.12',
  '1500m freestyle': '15:20.48',
  '50m backstroke': '26.86',
  '100m backstroke': '57.13',
  '200m backstroke': '2:03.14',
  '50m breaststroke': '29.16',
  '100m breaststroke': '1:04.13',
  '200m breaststroke': '2:17.55',
  '50m butterfly': '24.43',
  '100m butterfly': '54.33',
  '200m butterfly': '2:01.81',
  '200m individual medley': '2:05.70',
  '400m individual medley': '4:23.65'},
 'SC Men': {'50m freestyle': '19.90',
  '100m freestyle': '44.84',
  '200m freestyle': '1:38.61',
  '400m freestyle': '3:32.25',
  '800m freestyle': '7:20.46',
  '1500m freestyle': '14:06.88',
  '50m backstroke': '22.11',
  '100m backstroke': '48.16',
  '200m backstroke': '1:45.12',
  '50m breaststroke': '24.95',
  '100m breaststroke': '55.28',
  '200m breaststroke': '1:59.52',
  '50m butterfly': '21.32',
  '100m butterfly': '47.68',
  '200m butterfly': '1:46.85',
  '100m individual medley': '49.28',
  '200m individual medley': '1:48.88',
  '400m individual medley': '3:54.81'},
 'SC Women': {'50m freestyle': '22.83',
  '100m freestyle': '49.93',
  '200m freestyle': '1:49.36',
  '400m freestyle': '3:50.25',
  '800m freestyle': '7:54.00',
  '1500m freestyle': '15:08.24',
  '50m backstroke': '25.23',
  '100m backstroke': '54.02',
  '200m backstroke': '1:57.33',
  '50m breaststroke': '28.37',
  '100m breaststroke': '1:02.36',
  '200m breaststroke': '2:12.50',
  '50m butterfly': '23.72',
  '100m butterfly': '52.71',
  '200m butterfly': '1:59.32',
  '100m individual medley': '55.11',
  '200m individual medley': '2:01.63',
  '400m individual medley': '4:15.48'}}

In [32]:
import json
with open("records.json") as jf:
    gazapacho_records = json.load(jf)

In [35]:
gazapacho_records

{'LC Men': {'50m freestyle': '20.88',
  '100m freestyle': '46.40',
  '200m freestyle': '1:42.00',
  '400m freestyle': '3:39.96',
  '800m freestyle': '7:32.12',
  '1500m freestyle': '14:30.67',
  '50m backstroke': '23.55',
  '100m backstroke': '51.60',
  '200m backstroke': '1:51.92',
  '50m breaststroke': '25.95',
  '100m breaststroke': '56.88',
  '200m breaststroke': '2:05.48',
  '50m butterfly': '22.27',
  '100m butterfly': '49.45',
  '200m butterfly': '1:50.34',
  '200m individual medley': '1:52.69',
  '400m individual medley': '4:02.50'},
 'LC Women': {'50m freestyle': '23.61',
  '100m freestyle': '51.71',
  '200m freestyle': '1:52.23',
  '400m freestyle': '3:54.18',
  '800m freestyle': '8:04.12',
  '1500m freestyle': '15:20.48',
  '50m backstroke': '26.86',
  '100m backstroke': '57.13',
  '200m backstroke': '2:03.14',
  '50m breaststroke': '29.16',
  '100m breaststroke': '1:04.13',
  '200m breaststroke': '2:17.55',
  '50m butterfly': '24.43',
  '100m butterfly': '54.33',
  '200m butterfly': '2:01.81',
  '200m individual medley': '2:05.70',
  '400m individual medley': '4:23.65'},
 'SC Men': {'50m freestyle': '19.90',
  '100m freestyle': '44.84',
  '200m freestyle': '1:38.61',
  '400m freestyle': '3:32.25',
  '800m freestyle': '7:20.46',
  '1500m freestyle': '14:06.88',
  '50m backstroke': '22.11',
  '100m backstroke': '48.16',
  '200m backstroke': '1:45.12',
  '50m breaststroke': '24.95',
  '100m breaststroke': '55.28',
  '200m breaststroke': '1:59.52',
  '50m butterfly': '21.32',
  '100m butterfly': '47.68',
  '200m butterfly': '1:46.85',
  '100m individual medley': '49.28',
  '200m individual medley': '1:48.88',
  '400m individual medley': '3:54.81'},
 'SC Women': {'50m freestyle': '22.83',
  '100m freestyle': '49.93',
  '200m freestyle': '1:49.36',
  '400m freestyle': '3:50.25',
  '800m freestyle': '7:54.00',
  '1500m freestyle': '15:08.24',
  '50m backstroke': '25.23',
  '100m backstroke': '54.02',
  '200m backstroke': '1:57.33',
  '50m breaststroke': '28.37',
  '100m breaststroke': '1:02.36',
  '200m breaststroke': '2:12.50',
  '50m butterfly': '23.72',
  '100m butterfly': '52.71',
  '200m butterfly': '1:59.32',
  '100m individual medley': '55.11',
  '200m individual medley': '2:01.63',
  '400m individual medley': '4:15.48'}}

In [43]:
records == gazapacho_records

True

In [44]:
records["SC Women"]["100m butterfly"]

'52.71'

In [45]:
gazapacho_records["SC Women"]["100m butterfly"]

'52.71'